name: readme-recursion
description: An action to create cool recursive READMEs for your Github profile
author: Daan Koning
branding:
  icon: 'image'
  color: 'purple'

inputs:
  user:
    description: "The user for which the image is being generated. Default: the owner of the current repository."
    required: false
    default: 'false'
  auto-commit:
    description: "Whether or not to automatically commit the generated image. Default: false"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      if: ${{ inputs.auto-commit == 'true' }}
    - name: Install dependencies
      run: |
        curl https://raw.githubusercontent.com/daankoning/recursive-readme/main/requirements.txt | xargs pip install
      shell: bash
    - name: Fetch script
      run: |
        curl https://raw.githubusercontent.com/daankoning/recursive-readme/main/images.py >images.py
      shell: bash
    - name: Generate images
      run: |
        python images.py --user ${{ inputs.user }}
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update image
        file_pattern: example.png
      if: ${{ inputs.auto-commit == 'true' }}
        
