name: readme-recursion
description: An action to create cool recursive READMEs for your Github profile
author: Daan Koning
branding:
  icon: 'image'
  color: 'purple'

inputs:
  auto-commit:
    description: "Whether or not to automatically commit the generated image. Default: false"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      if: ${{ inputs.auto-commit == 'true' }}
    - name: Install dependencies
      run: |
        curl https://raw.githubusercontent.com/daankoning/recursive-readme/main/requirements.txt | xargs pip install
      shell: bash
    - name: Generate image
      run: |
        curl https://raw.githubusercontent.com/daankoning/recursive-readme/main/images.py | python
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update image
        file_pattern: example.png
      if: ${{ inputs.auto-commit == 'true' }}
        
