name: readme-recursion
description: An action to create cool recursive READMEs for your Github profile
author: Daan Koning
branding:
  icon: 'image'
  color: 'purple'

inputs:
  user:
    description: "The user for which the image is being generated. Default: the owner of the current repository."
    required: false
    default: 'false'
  auto-commit:
    description: "Whether or not to automatically commit the generated image. Default: false"
    required: false
    default: 'false'
  output-file:
    description: "The file where the recursive image is output. Default: /example.png"
    required: false
    default: 'example.png'
  tag-id:
    description: "The id of the img tag in your README. Default: recursivereadme"
    required: false
    default: 'recursivereadme'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      if: ${{ inputs.auto-commit == 'true' }}
    - name: Get current tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      shell: bash
    - name: Install dependencies
      run: |
        curl https://raw.githubusercontent.com/daankoning/recursive-readme/${{ env.RELEASE_VERSION }}/requirements.txt | xargs pip install
      shell: bash
    - name: Fetch script
      run: |
        curl https://raw.githubusercontent.com/daankoning/recursive-readme/${{ env.RELEASE_VERSION }}/images.py >images.py
      shell: bash
    - name: Generate images
      run: |
        python images.py --user ${{ inputs.user }} --output-file ${{ inputs.output-file }} --tag-id ${{ inputs.tag-id }}
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update image
        file_pattern: example.png
      if: ${{ inputs.auto-commit == 'true' }}
        
